import type { SpatialSchemaVersion } from './index'

const fixtureFreshness = {
  state: 'FRESH',
  observed_at: '2026-09-05T12:00:00-04:00',
  stale_after_seconds: 300,
  source: 'dashboard-fixture',
} as const

export const spatialContractFixtures = {
  goodAgent: {
    schema_version: 'spatial.entity.v1',
    kind: 'agent',
    id: 'agent-primary-fixture',
    canonical_ref: 'agent:primary-fixture',
    node_id: 'node-fixture-01',
    revision: '7',
    label: 'Primary Agent',
    state: 'ready',
    availability: 'available',
    freshness: fixtureFreshness,
    created_at: '2026-09-05T15:00:00Z',
    updated_at: '2026-09-05T16:00:00+00:00',
    role: 'primary',
    binding_ref: 'binding-fixture-01',
    capability_refs: ['hypervisor.read', 'resource.inspect'],
    additive_dashboard_field: 'accepted and stripped',
  },
  staleEndpoint: {
    schema_version: 'spatial.entity.v1',
    kind: 'endpoint',
    id: 'endpoint-fixture-01',
    canonical_ref: 'endpoint:fixture-01',
    node_id: 'node-fixture-01',
    revision: 12,
    label: 'Fixture Endpoint',
    state: 'degraded',
    availability: 'degraded',
    freshness: {
      ...fixtureFreshness,
      observed_at: '2026-09-05T10:00:00Z',
    },
    created_at: '2026-09-05T09:00:00Z',
    updated_at: '2026-09-05T10:00:00Z',
    endpoint_type: 'inference',
    capability_refs: ['inference.generate'],
    provider_ref: 'provider-fixture-01',
  },
  partialStatus: {
    schema_version: 'spatial.node-status.v1',
    node_id: 'node-fixture-01',
    revision: 19,
    state: 'degraded',
    observed_at: '2026-09-05T12:01:00Z',
    freshness: {
      ...fixtureFreshness,
      state: 'partial',
      source: 'dashboard-partial-fixture',
    },
    components: [
      {
        component_id: 'hypervisor-fixture-01',
        component_type: 'Hypervisor',
        state: 'running',
        observed_at: '2026-09-05T12:01:00Z',
        freshness: fixtureFreshness,
        source: 'probe.hypervisor',
      },
      {
        component_id: 'mcp-fixture-01',
        component_type: 'MCP Server',
        state: 'unknown',
        observed_at: '2026-09-05T11:55:00Z',
        freshness: { ...fixtureFreshness, state: 'unknown', source: 'probe.mcp' },
        source: 'probe.mcp',
      },
    ],
  },
  malformedRelation: {
    schema_version: 'spatial.relation.v1',
    relation_id: '',
    node_id: 'node-fixture-01',
    revision: 2,
    relation_type: 'produced_by',
    source_ref: 'agent:primary-fixture',
    target_ref: 'artifact:fixture-01',
    state: 'active',
    freshness: fixtureFreshness,
    created_at: 'not-a-timestamp',
    updated_at: '2026-09-05T12:00:00Z',
    private_key: 'fixture-secret-must-never-enter-a-diagnostic',
  },
  incompatibleEntityVersion: {
    schema_version: 'spatial.entity.v2',
    kind: 'agent',
  },
  goodWorkspace: {
    schema_version: 'spatial.workspace.v1',
    workspace_id: 'workspace-node-fixture-01',
    node_id: 'node-fixture-01',
    revision: 21,
    semantic_revision: 21,
    created_at: '2026-09-05T09:00:00Z',
    updated_at: '2026-09-05T12:01:00Z',
    entities: [],
    relations: [],
    semantic_anchors: [],
    primary_agent_ref: 'agent:primary-fixture',
  },
  goodViewport: {
    schema_version: 'spatial.viewport.v1',
    workspace_id: 'workspace-node-fixture-01',
    node_id: 'node-fixture-01',
    device_id: 'device-fixture-desktop',
    presentation_revision: 3,
    camera: { x: 0, y: 0.42, zoom: 1, focus_id: null },
    selection_ref: null,
    opened_frame_refs: [],
    temporary_focus_ref: null,
    transient_discovery_refs: [],
    quality_profile: 'desktop',
    updated_at: '2026-09-05T12:01:00Z',
  },
  unassignedPrimaryAgentSlot: {
    schema_version: 'spatial.primary-agent-slot.v1',
    slot_id: 'primary-slot-node-fixture-01',
    node_id: 'node-fixture-01',
    current_binding_id: null,
    lifecycle_state: 'UNASSIGNED',
    revision: 0,
    assigned_at: null,
    assigned_by: null,
    last_seen_at: null,
    capability_grant_ref: null,
    hook_subscription_ref: null,
    durable_inbox_ref: 'inbox-primary-slot-node-fixture-01',
    changed_at: '2026-09-05T12:01:00Z',
  },
  primaryAgentGrant: {
    schema_version: 'spatial.primary-agent-grant.v1',
    grant_id: 'grant-node-fixture-01',
    node_id: 'node-fixture-01',
    binding_id: 'binding-node-fixture-01',
    revision: 1,
    categories: ['read', 'action'],
    allowlisted_tools: ['resource.inspect', 'hooks.receive'],
    redaction_profile_ref: 'redaction-default',
    state: 'ACTIVE',
    issued_at: '2026-09-05T12:01:00Z',
    issued_by: 'operator:fixture',
    expires_at: null,
  },
  primaryAgentState: {
    schema_version: 'spatial.primary-agent-state.v1',
    node_id: 'node-fixture-01',
    slot_id: 'primary-slot-node-fixture-01',
    binding_id: 'binding-node-fixture-01',
    state: 'READY',
    attention_severity: 'NONE',
    source: 'probe.primary-agent',
    revision: 1,
    observed_at: '2026-09-05T12:01:00Z',
    last_successful_response_at: '2026-09-05T12:00:00Z',
    last_failed_response_at: null,
  },
} as const satisfies Record<string, Record<string, unknown> & { schema_version: SpatialSchemaVersion | string }>
